sudo: required
services:
  - docker

# test client - could also test the other services here
before_install:
  - docker build -t bradypp/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run bradypp/client-test npm test -- --coverage

after_success:
  - docker build -t bradypp/multi-client ./client
  - docker build -t bradypp/multi-nginx ./nginx
  - docker build -t bradypp/multi-server ./server
  - docker build -t bradypp/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push bradypp/multi-client
  - docker push bradypp/multi-nginx
  - docker push bradypp/multi-server
  - docker push bradypp/multi-worker
deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: docker-multi
  env: Dockermulti-env
  bucket_name: elasticbeanstalk-eu-west-1-212426572662
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
